# Generated by Django 5.1.3 on 2024-11-23 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme_sysoev', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlike',
            old_name='liked_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('user', 'answer')},
        ),
    ]
